#!/bin/bash

# Use image label to cleanup possible orphaned images.
oImgs=$(buildah images | grep -F '<none>' | awk '{print $3}')
for img in $oImgs ; do
    if buildah inspect $img | grep -q '"AUTOMATION_CONTAINER_IMAGE": "api-infoblox"'; then
        buildah rmi --force $img
    fi
done

if [ "$1" == "purge" ]; then
    if podman volume ls | awk '{print $2}' | grep -q ^api-infoblox$; then
        printf "\n* Clean up api-infoblox volume...\n"
        podman volume rm api-infoblox
        podman volume rm api-infoblox-db
        podman volume rm api-infoblox-cacerts
    fi
fi

# De-schedule db backups.
(crontab -l | sed '/bck-db_api-infoblox.sh/d') | crontab -

exit 0
